### ISSUE TITLE
Requirements and style feedback

### ISSUE THREAD

**Issue by listguy** [kosta1221/react-pokedex#4]
Amazing job guys 👏
Smooth UX, beautiful UI and a very good pokedex!
A few notes:
- Great implementation of sprites bonus
- The auto complete is very cool and looks good 
- Spinner smooth and done correctly
- 404 message is too simple 👎 We wanted a cool one!
- Why are you fetching two sprites for each pokemon?
- When collection is empty a small yellow with blue border `div` is displayed. Isn't a message ("No pokemon caught!") would be nicer? 

@kosta1221 
@michefraim

**Comment by kosta1221** [comment]
Oh my, I can't believe I somehow missed this and am just seeing this now! 
Anyways, thanks a lot Nitzan, this is some really thought-provoking feedback. Agree 100% about the 404. 
About the 2 sprites for each pokemon - We really liked the aesthetic of the other kind of "banner" sprite and it is 100% intentional. 
About your last point I actually did it on March 22nd (commit id: dfae0c68c28524e7dbca0bc05ab07f00eaebaf9e title : "display message for trying to view empty collection") and forgot to host this build! Talk about the importance of a good and automated workflow...
 
@listguy

**Comment by kosta1221** [comment]
I took care of it and the version with the display message is now deployed so you can check it out if you'd like. Thanks again for the great feedback. :)

P.S The 2 sprites are just great for the vertical flexbox style on mobile in my opinion, what do you think? Would you leave the 2 sprites or just keep 1?

![WhatsApp Image 2021-04-06 at 14 37 20](https://user-images.githubusercontent.com/76045173/113705096-b26b8480-96e5-11eb-8b4b-540add61cb18.jpeg)

**Comment by listguy** [comment]
Looks awesome but I prefer one. If you really liked the sharper sprites (the bottom ones) just use them instead 👍

**Comment by kosta1221** [comment]
Okay thank you! I'll talk to @michefraim about it and I think we'll go with keeping 2 sprites for mobile and maybe 1 for bigger screens.
